baseURL = "https://www.jamesh.id.au/"
languageCode = "en-au"
title = "James Henstridge"
theme = "ananke"
paginate = 100
enableGitInfo = true
enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "monokai"

[permalinks]
blog = "/blog/:year/:month/:slug/"

[params]
mainSections = ["post"]
disable_share = true

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/jameshenstridge"
[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/james.henstridge"
[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/jameshenstridge/"
[[params.ananke_socials]]
name = "github"
url = "https://github.com/jhenstridge"

[related]
threshold = 80
includeNewer = true
toLower = false
[[related.indices]]
name = "keywords"
weight = 100
[[related.indices]]
name = "tags"
weight = 50
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"
