baseURL = "http://www.jamesh.id.au/"
languageCode = "en-au"
title = "James Henstridge"
theme = "ananke"
paginate = 100
pygmentsStyle = "solarized-light"
disablePathToLower = true

[params]
facebook = "https://www.facebook.com/james.henstridge"
twitter = "https://twitter.com/jameshenstridge"
linkedin = "https://www.linkedin.com/in/jameshenstridge/"
github = "https://github.com/jhenstridge"
mainSections = ["post"]

[related]
threshold = 80
includeNewer = true
toLower = false
[[related.indices]]
name = "keywords"
weight = 100
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "https://blogs.gnome.org/jamesh/"
weight = 1
